

# ============ Kuiper Platform
# NOTE: Kuiper IP and PORT will not be used anymore since gunicorn will handle the requests, see and change Gunicorn section instead 
Kuiper:
  Debug:          True            # enable debugging mode       # deprecated since gunicorn will handle the sessions 
  RemoveRawFiles: True            # remove raw files uploaded to Kuiper, as consequences enable this will allow upload the file multiple times
  installer:      ./kuiper_install.sh
  logs_level:     DEBUG            # log level stored in the app logs (INFO, WARNING, DEBUG, and ERROR)
  api_token:      WWUFMHVvPEBBdXtLfm6DyyJpNkQ8DqFNuhdZkZvbc7HW5bjs765kmGGE9wLHkCEjShwLzmrmSW9zBBGj48zUdg9yGFg7YyLY82KLk2dRuYbUX8WGBYCpGguAtv9FMFdft2U8AA7nTHwja4ATQgpBF68PBkaaPtv5FUcwdhGEqXE3nXUSYH2xSGByNGB4utqP6FFDGp7pzg3rsUZt5f8KY9svMesWNdVmujVQMCgfQyQmS9pDYPe8wzsrqqTwQv8eSRhwy5Gn4Uz6cTFUraxhwzUBwEHN7ue9w5C7vvmT9PF9GpyjuWnkK6Wf6tdLyPEeUfUp9xSTjetYMnMeMSGfP2ASy7unETaKaEMxBzbXCZCskwPS36jk8bE6drJASP8UVwfBNswHL6JdRsrbHFcP3PNF5rhRyrJwB8phw8zYBUN3kbuRj5ZGGTSFzXQP9D377jWQKEqnE9XcCxRLQPSq96SZhAedMe3zePzrEpRcpQXBhULtTvxESwVcW47Ncr7AkNmCKBUeJYLAFJJqfFXYsGAhvFjj6LWmqX4jcgGyxbBE3HzMfvaEwv7rk7AaawT53MhkwT8P6W3PdfjGt28LfBvM9kwJArbudTxPFcmH5a4fkSqNCLZnjZ7GvV6BnC6EBcuyKfeuAqgwLWNagDWhuHrQ2N93cBxX7nHASGVdgTRg5EFrP9rbn3xRY8CeH98DaZnYH7PMyXQttXBjqbX5943shswDed9qGH3S36TAqbTxKcZv23MafKNm42ubANEPJbpJpV2upfFWF4bJ3mDxnnPRz8XWLSFjS6Qc3sVh4HeYRpKkPEJTPRTcvUvks9QadCyqBPqCSMPvsNb7jCSSqA43ZMvpPkRj7uyNxPHRCKskuahQ9bFtuyrT7wrqYduA3k9qrJ9xSu6LhwQy3tt2KtKpCYZ6Eq3ckGXwyFD7rV5sPhuu5UjAHt6DTxGuRcxKruupgPFNk5EjPpYef3g9M2zyh8tmVaMQcgEsMpyTE3TswkkKnynA8Tzb8zBUrkrpxK6CEspba7ufL8XYmXjcEZXXAXzUU5bkwTT4d85J7PLWMrJnvQu3K2eEPvWYu5v5WJqTnGLRjwrbrVdhkg9Bt73PSk754Utb925bgVg92zxt9gf7Kj5LkyzwqjvZ4seLPuyPEkxKCVZn62WRbPpTVQLkmHzAfRnaUcEN6BpdtgD6GaHTRfLuJJpfjxgJ6MdpE83c6uSfrMC6bGcqLRwaHM8qM9ZybQtaztfyTDZs2C9J5WZB3g9RtbDdkVbazUnZRaffJUQjFSQjQkgkP7TYSsTsA3Ep5wdsyGbshLh2mFuEsFLThDVU8KBbQbaU9nkRNcXZXDzkzcvTKqKNhH5cEh22syPPY4HVb4EgLenxWt2ba8NArzAGp9hd5EsjNpZaHP8SX7Dd5HPJFjLvj9XxVwBEkHVLR96byhhtk89AMCRydABwzhfNLDJktvwyQufpugkrzk9PCMh4tgzUyFfuvuC3gcNFrwHsMpNhFQFCvpjG7cDwRusfERRgMr8RELMW67mDNU658crCqBKruyqVrhdYSNKxxACWpnMQFs62LXV59Uh3WXcADWvsdcF9me5cUS7ks2sa6JEGU3fgCY6T3LQ5zXqZgAZtFStf6EJztGrB5HNKxn9sBX6LeBSLj6cjxBCzwpJsh5Ef4MPCGmkEU4ntDLXrpNdYyQ6XJGbvNTtSfaE4qJ6YEhv22x7eSnC65jWaQsmgQdrpsFn6gkqn93PKhkGDSSr9c8p7nKkCQaTGcgKBRMyrRJP4RyYagnVFpbLrQfGL94TLS3Ze2eC5WLHAA4TUs3TB9w4QkknQdtNuDExfD6YAJwW8u9VpDXcLC4MwjCqmQsfBttLZ29yBwcZ3Ff45X2dhgPpFfy3cQLLGTbEpatKgXkCbGQhgpwjCbXC6CT8EFP5kFTPtvAzfCPpsGU3JA8PELyHyx2KVQe3jzpSFEE6DLmH4sBRKWFmTBxZaXfke8jsquN9578hQVNsdg8y2v8GRANr6rrawf6Q6tK8P8z86DzhXgMxJGNDk
  secret_key:     =Rs--[/\n(T,f+:H"]w4C6H8Yy\!wNurz+R@QFU~9;7A<LbR>;xC,\Aa%ZET}j7M!\</7SM~*NUdYQ}x+HTZHFMt8"<U_N?Lyr;n+w5vg.6N@L_g,C?n8X~rN?A:*jZ#

# ============ LDAP authentication

LDAP_auth:
  enabled: false
  LDAP_HOST: '10.10.10.10'
  LDAP_PORT: '636' 
  LDAP_SCHEMA: 'ldaps'
  LDAP_USE_SSL: True
  LDAP_BASE_DN: 'OU=Users,DC=Domain,DC=local'
  LDAP_USERNAME: 'CN=ldap-bind,CN=Users,DC=Domain,DC=local'           # ldap bind username
  LDAP_PASSWORD: 'bind account pass'                                  # ldap bind password
  LDAP_USER_OBJECT_FILTER: '(&(objectclass=user)(samaccountname=%s))' # this query to confirm if user exists or not if correct


# ============ Gunicorn configuration
# gunicorn used to support multi-request connections at the same time, gunicorn will run Flask platform and handle requests to it
Gunicorn:
  IP:           unix           # gunicorn LISTEN IP address
  PORT:         kuiper.sock               # gunicorn LISTEN PORT number
  Threads:      6                 # gunicorn number of thrads
  worker_class: gevent            # gunicorn workder class
  timeout:      3600              # gunicorn request timeout 1h 
  workers:      4                 # gunicorn number of workers
  cert_key:     cert/MyKey.key     # SSL key ptath 
  cert_cert:    cert/MyCertificate.crt   # SSL certificate path 


# ============ AdminLTE
adminlte:
  SIDEBAR_OPEN: False             # by default the left sidebar of platform closed


# ============ configuration of celery
CELERY:
  CELERY_BROKER_URL:      redis://localhost:6379
  CELERY_RESULT_BACKEND:  redis://localhost:6379
  CELERY_WORKER_NAME:     worker@kuiper
  CELERY_TASK_ACKS_LATE:  True,
  celery_task_name:       'task.parser.kuiper'

# ============ Elasticsearch
ElasticSearch:
  IP    : 0.0.0.0
  PORT  : 9200


# ============ MongoDB
MongoDB:
  DB_NAME: 'Kuiper'         # MongoDB Database name
  DB_IP: '127.0.0.1'        # MongoDB Database IP address 
  DB_PORT: 27017            # MongoDB Database Port number


# ============ Git
Git:
  git_url_release : 'https://api.github.com/repos/DFIRKuiper/Kuiper/releases/latest'                                     # link for git to pull new updates if exists
  k_version       : "v2.0.10"                                                                          # current version of kuiper

# ============ Logs
Logs:
  log_folder:   ./logs/                     # store the logs folder 
  install_log:  Kuiper-install.log
  access_log:   Kuiper-access-gunicorn.log
  app_log:      Kuiper-flask.log
  celery_log:   Kuiper-celery.log
  update_log:   Kuiper-update.log
  gunicorn_pid: gunicorn.pid
  kuiper_log:   Kuiper.log
  

# ============ configuration of directories on the platform
# it is preferable to not change these settings (except platform_folder)  
Directories:
  platform_folder: &platform_folder   "./"                                 # main folder
  app_folder: &app_folder             [*platform_folder, /app]          # application files folder
  app_parsers:                        [*platform_folder, /app/parsers]  # parsers folder
  artifacts_upload:                   [*platform_folder, /files]        # uploaded artifacts folders  
  artifacts_upload_raw:               [*platform_folder, /raw]          # original uploaded compressed files


# ============ case_sidebar
# Title content: [<title on sidebar>,<url path>,<icon>]
# SubTitles: [ [ <title on sidebar>,<url path>,<icon>] , etc. ]
case_sidebar:
  - Title: ["Administrator" , "/admin/" , "fa fa-tv"]
    SubTitles: Null
  - Title: ["Dashboard","/case/<case_id>/dashboard","fa fa-pie-chart"]
    SubTitles : Null
  - Title: ["Machines","/case/<case_id>","fa fa-laptop"]
    SubTitles : Null
  - Title: ["Artifacts","/case/<case_id>/browse_artifacts","fa  fa-cubes"]
    SubTitles : Null
  - Title: ["Timeline","/case/<case_id>/timeline","fa fa-clock-o"]
    SubTitles : Null
  - Title: ["Alerts","/case/<case_id>/alerts","fa  fa-bell"]
    SubTitles : Null
  - Title:      ['Logout' , '/logout' , 'fa fa-sign-out']
    SubTitles : Null

# ============ admin_sidebar
# Title content: [<title on sidebar>,<url path>,<icon>]
# SubTitles: [ [ <title on sidebar>,<url path>,<icon>] , etc. ]
admin_sidebar:
  - Title:      ["Cases","/admin/","fa  fa-globe"]
    SubTitles : Null
  - Title:      ['Rules' , '/admin/rules' , 'fa fa-list-alt']
    SubTitles : Null
  - Title:      ['Settings' , '#' , 'fa fa-gears' ]
    SubTitles : [
          ['Configuration' , '/admin/config' , 'fa fa-gears'],
          ['Health' , '/admin/system_health' , 'fa fa-gears'],
          ['About' , '/admin/update' , 'fa fa-gears']
      ]
  - Title:      ['Logout' , '/logout' , 'fa fa-sign-out']
    SubTitles : Null